# This workflow will build a Java project with Gradle.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
#  schedule:
#    - cron:  '*/15 * * * *'
#  cancel-runs:
#  # Prevent forks from running this to be nice
#  if: github.repository == 'foo-org/my-repo'
#  runs-on: ubuntu-latest
#    steps:
#        - uses: n1hility/cancel-previous-runs@v2
#          with:
#            token: ${{ secrets.GITHUB_TOKEN }}
#            workflow: my-heavy-workflow.yml

jobs:
  build:

    runs-on: self-hosted

    steps:
     - uses: actions/checkout@v2
     - uses: n1hility/cancel-previous-runs@v2
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     - name: Copy bot token
       run: cp -f ~/BotToken.java ~/actions-runner/_work/SlaveBot/SlaveBot/src/main/java/bot/slave
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Clean with Gradle
       run: ./gradlew clean
     - name: Build with Gradle
       run: ./gradlew shadowJar
     - name: Make resources directory
       run: mkdir ~/actions-runner/_work/SlaveBot/SlaveBot/build/libs/resources
     - name: Copy resources
       run: cp -f ~/actions-runner/_work/SlaveBot/SlaveBot/resources/Jokes.txt ~/actions-runner/_work/SlaveBot/SlaveBot/build/libs/resources

  deploy:
    runs-on: self-hosted
    steps:
     - name: Run SlaveBot
       run: java -jar ~/actions-runner/_work/SlaveBot/SlaveBot/build/libs/SlaveBotShadow.jar
